### ISSUE TITLE
Some problems still persist due to the line height of the bold font

### ISSUE THREAD

**Issue by peeofive** [jenskutilek/FiraSystemFontReplacement#14]
The message count in Mail
The mailboxes button (which hides and shows the mailboxes)
The tabs in iTerm

Otherwise it's totally great!

**Comment by afincato** [comment]
the only thing about line-height which is still a problem, is the text in the search bar in Safari.

![screen shot 2015-02-16 at 16 10 05](https://cloud.githubusercontent.com/assets/5596183/6214095/7094c336-b5f6-11e4-9224-16a96bc3ef8d.png)
