### ISSUE TITLE
Text for battery percentage and Safari address bar is too high

### ISSUE THREAD

**Issue by vandrijevik** [jenskutilek/FiraSystemFontReplacement#17]
With the latest release, the baseline went up too much:

![screen shot 2014-11-09 at 14 07 57](https://cloud.githubusercontent.com/assets/7736/4967441/a1613a9a-6811-11e4-9b7c-b8bdd70ed400.png)

and

![screen shot 2014-11-09 at 14 08 04](https://cloud.githubusercontent.com/assets/7736/4967442/a3fc918c-6811-11e4-9f09-09476b98c714.png)

**Comment by faroit** [comment]
:+1:

**Comment by jenskutilek** [comment]
This is fixed in the El Capitan branch, won't fix for Yosemite (because I don't know how).
