### ISSUE TITLE
App store dialog font broken

### ISSUE THREAD

**Issue by Nizm** [jenskutilek/FiraSystemFontReplacement#20]
Every app store popup on osx seems broken. 

![screen shot 2014-11-12 at 10 55 00 am](https://cloud.githubusercontent.com/assets/22054/5013284/78b3696a-6a5a-11e4-83d1-0c37aa74ea4a.png)

**Comment by jenskutilek** [comment]
Is anyone still having this problem? I saw these fallback characters once in the login dialog. Shutting down the computer, turning it off and on again resolved it.

**Comment by emmajane** [comment]
Same for me when the Terminal window spawns a keychain request (e.g. if I'm working with Git and need to authenticate myself from the command line). I tried with the latest version of the font and can confirm the problem exists as of today.
![font-error](https://cloud.githubusercontent.com/assets/1299320/6205413/40906cc8-b53b-11e4-8033-effc90226de0.png)

**Comment by rauberdaniel** [comment]
@emmajane You copied the font files in `/Library/Fonts/`, correct? Not in `~/Library/Fonts` as mentioned in #11.

**Comment by emmajane** [comment]
Aha! That did solve it for me. Thanks!
