### ISSUE TITLE
Name of current user is offset in menu bar

### ISSUE THREAD

**Issue by mbrennwa** [jenskutilek/FiraSystemFontReplacement#23]
Mac OS X displays the name of the currently logged in user in the menu bar, just next the the time and the Spotlight magnifying glass. With Fira in place, the user name is vertically offset. With the standard Helvetica Neue font, alignment is ok.

**Comment by verpixelt** [comment]
Same issue with the numbers of the battery percentage display. 
![menu-bar-osx](https://cloud.githubusercontent.com/assets/1640079/6731615/59b58ca0-ce46-11e4-8150-1a53db620ada.png)

**Comment by jenskutilek** [comment]
This is fixed in the El Capitan branch, won't fix for Yosemite (because I don't know how).
