### ISSUE TITLE
Superscript numbers in Quicktime

### ISSUE THREAD

**Issue by rauberdaniel** [jenskutilek/FiraSystemFontReplacement#25]
As you can see in the attached screenshot, the numbers 1,2 and 3 are in superscript in Quicktime. The numbers 0,4,5,6,7,8,9 are correctly aligned.

![Screenshot](https://cloud.githubusercontent.com/assets/447405/5339040/774dc17a-7edb-11e4-917b-30ce0edb7da4.png)

**Comment by jenskutilek** [comment]
Fixed superscript issue in b41273fd37.
