### ISSUE TITLE
Vertical alignment a bit off overall

### ISSUE THREAD

**Issue by hgranholm** [jenskutilek/FiraSystemFontReplacement#27]
Hello!

I hate to complain, because this is AWESOME. Thank you for saving my eyes.

But anyway: the vertical alignment in places is a tiny bit off in places. For example: too low in window titles & system menu. Too high in Safari & Finder tabs and safari URL box. I'm talking about one non-retina pixel here, but hey I think we are in fine-tuning territory already :-P

I realise this might be difficult to fix, but you know, it is reported now :-)
Harri

**Comment by lmartins** [comment]
+1 on this one. Loving Fira so far, but what put's a bit off about is those exact misalignments @hgranholm refers to.

**Comment by kopischke** [comment]
+1 here too. Very visible in the Mail.app column display (subtitle alignment):

![Mail.app screenshot](https://cloud.githubusercontent.com/assets/80906/6714886/138e0df2-cd9b-11e4-886c-d333d934e2c4.png)

**Comment by MrAlexWeber** [comment]
Not sure if this should be a separate issue, but it seems to be the same one—vertical alignment is off in Notifications. Attaching some screenshots to illustrate the point.
![screen shot 2015-03-25 at 10 04 16 am](https://cloud.githubusercontent.com/assets/463469/6831531/0d20f586-d2de-11e4-91a2-7a11b701fd14.png)
Here you can see the Messages notification looks correct, while Facebook's appears to have a blank line above.
Here's another example:
![screen shot 2015-03-25 at 10 54 21 am](https://cloud.githubusercontent.com/assets/463469/6831532/0d33abea-d2de-11e4-9f1c-1f50a0acedda.png)

PS - I'm on 10.10.2, in case it matters.

**Comment by miloshadzic** [comment]
I think this is a general issue with Fira.

**Comment by alexkrolick** [comment]
Fira does have some unusual line heights relative to other types, but I have heard of alignment issues occurring in the same places when replacing the system font with e.g., [San Francisco](http://gizmodo.com/yeah-the-username-is-a-weird-anomaly-what-the-hell-1668483170).

**Comment by jenskutilek** [comment]
I think the UI is just very finely tuned to the specific metrics of Helvetica, so it can’t fit in all places when using a different font. At least I don’t have any idea how to fix the remaining issues without breaking other things ...

**Comment by Midar** [comment]
The misalignments are especially bad if you show the battery percentage in the menu bar. All in all, the whole menu bar looks completely off. Same for tabs and the URL bar in Safari. Or all buttons in general. The text always has too much spacing on the bottom and umlauts like Ü almost hit the line above, which looks very wrong when a menu entry with an Ü is highlighted (the dots of the Ü are almost in the row above!). On the other hand, this edit box here right now has all text glued to the bottom and a lot of spacing on the top. Both misalignments looks extremely wrong on both, Retina and non-Retina. It's so bad that this is actually causing me to not use the font, even though the font itself looks really nice. But having vertical spacing completely broken drives me nuts.

**Comment by NetOpWibby** [comment]
The usual misalignment I used to see prior to the El Capitan-ready version, is gone. Everyone else should upgrade and check it out too.

**Comment by hgranholm** [comment]
This is great news—thanks for the heads up! I think I'll wait a couple of days for the El Capitan 1.0 release first though :-)

The new Apple font is of course a huge improvement, but Fira is still better. The shape is closer to Fira, so maybe this is the reason why it now aligns better?

**Comment by jenskutilek** [comment]
This is fixed in the El Capitan branch, won't fix for Yosemite (because I don't know how).

**Comment by hgranholm** [comment]
Cheers :-)
