### ISSUE TITLE
Dialog Texts garbled

### ISSUE THREAD

**Issue by nevioth** [jenskutilek/FiraSystemFontReplacement#28]
Hi, 

I'm not sure why this is happening. The text is garbled on Dialogues like that: 
Running OS X 10.10.3 (14D136)

![screen shot 2015-06-04 at 14 48 25](https://cloud.githubusercontent.com/assets/2669729/7983476/59033266-0ac9-11e5-9a5a-bc71e9e53043.png)

Note: Maybe missing info, i'm using hebrew as a secondary language (Hebrew) in the OS, the interface language is English though.

**Comment by sebastianbeyer** [comment]
maybe related to this?: https://github.com/jenskutilek/FiraSystemFontReplacement/issues/18

**Comment by nevioth** [comment]
Thank You! 

Indeed moving the fonts to /Libary/Fonts and logging out fixed the problem.

**Comment by jenskutilek** [comment]
Good to see this solved!

So you probably didn’t use the installer package ... it is the safest way to install the fonts, because it puts the fonts into the right folder and also sets the file permissions correctly.
