### ISSUE TITLE
El Capitan Support?

### ISSUE THREAD

**Issue by NetOpWibby** [jenskutilek/FiraSystemFontReplacement#29]
I know this is a long shot, as  is clamping down on access to system files, but is this possible?

**Comment by mickeyl** [comment]
I'd also love to do that. San Fransisco looks like a step back now that I have El Capitan on my computer.

**Comment by jenskutilek** [comment]
El Capitan is now supported in f3e81602b8 respectively [release v4.106](https://github.com/jenskutilek/FiraSystemFontReplacement/releases/tag/v4.106). I've been using it myself for about 2 weeks now, but you're welcome to try it out and report any issues there may be hiding :)

**Comment by NetOpWibby** [comment]
It works beautifully, thank you so much! :dancer:

**Comment by sampotts** [comment]
Any chance this could be used to patch and install other fonts? It'd be awesome if so.
