### ISSUE TITLE
Space between letters in Finder list mode

### ISSUE THREAD

**Issue by hurlebouc** [jenskutilek/FiraSystemFontReplacement#31]
Hello !

I have a problem with horizontal spacing il list view in the finder: distance between letters is to large. 
<img width="60" alt="list_view" src="https://cloud.githubusercontent.com/assets/1151232/10241142/33a54192-68e5-11e5-82cc-e80793e1e66a.png">
<img width="259" alt="list" src="https://cloud.githubusercontent.com/assets/1151232/10241171/b7b4741c-68e5-11e5-8109-c95bfb7c7a8a.png">

But it is good in icon view.
<img width="54" alt="icon_view" src="https://cloud.githubusercontent.com/assets/1151232/10241145/39ea2cf2-68e5-11e5-8f2b-016bf6429492.png">
<img width="591" alt="icon" src="https://cloud.githubusercontent.com/assets/1151232/10241172/bc8d6c1e-68e5-11e5-8894-eeee397a9d17.png">

How can I solve this problem?

**Comment by hermosawave** [comment]
Yes, I'm having this problem too. Letter spacing is too wide in the Finder, but fine most other places (not completely sure)

Column View, that's mostly all I use.

Thanks Jens, I really appreciate your efforts on this.

Regards,
Daniel

**Comment by jenskutilek** [comment]
Thanks for reporting. This issue is fixed in 5920b2ae55d78d504983494cce0eba392963483c. Please download the new release and try it.

**Comment by hurlebouc** [comment]
Thank you, it's better!
