### ISSUE TITLE
Use of custom fonts 

### ISSUE THREAD

**Issue by chrisetheridge** [jenskutilek/FiraSystemFontReplacement#32]
Is it possible to integrate the use of custom fonts? The installer can ask for a location to the font .ttf and use that as the patch font.

**Comment by focusmade** [comment]
I would love this feature also. All I want is Open Sans on my mac again.

**Comment by NetOpWibby** [comment]
Is this project still being worked on? I'd love to try Operator Mono as a system font.

**Comment by chenpanliao** [comment]
I think the object of this project is not use of custom fonts.
Take a look of the following project:
https://github.com/dtinth/YosemiteAndElCapitanSystemFontPatcher

**Comment by jenskutilek** [comment]
I have written down some notes on the build process in [BUILD.md](https://github.com/jenskutilek/FiraSystemFontReplacement/blob/sierra/BUILD.md), hope that helps.
