### ISSUE TITLE
Error messages / App Store dialogs

### ISSUE THREAD

**Issue by jkmaxwell** [jenskutilek/FiraSystemFontReplacement#34]
This doesn't seem to work for system error messages and app store alerts (e.g., you've been signed out of the app store, please sign in again to update).

**Comment by jenskutilek** [comment]
It is a known issue that is hard to reproduce ... you could try the steps in this discussion https://github.com/jenskutilek/FiraSystemFontReplacement/issues/20 and see if that fixes it.

**Comment by jenskutilek** [comment]
I haven’t seen this in the current version. Please reopen if if happens again.
