### ISSUE TITLE
Squares (tofu) appear on system update screens after uninstalling

### ISSUE THREAD

**Issue by jyuhuan** [jenskutilek/FiraSystemFontReplacement#37]
I uninstalled the font following the instruction repeated below

> Delete or move all font files called `FSText-*.otf` and `FSDisplay-*.otf` from the `/Library/Fonts` folder

Everything was fine, except for when I did a system update, the following screens shows up:
![image](https://cloud.githubusercontent.com/assets/4944003/18188507/b6ed5a3c-7080-11e6-9e8a-cce2803762de.png)
![image](https://cloud.githubusercontent.com/assets/4944003/18188514/bd942640-7080-11e6-8efd-06993e372db9.png)

How can I remedy this?

**Comment by jenskutilek** [comment]
Try to completely turn off the computer once. Something of the fonts seems to stay present even across simple reboots.

**Comment by jyuhuan** [comment]
Do you know a best way to "completely turn off the computer", @jenskutilek ? I have already done it many times by selecting the "shut down" option from the Mac menu.

**Comment by jenskutilek** [comment]
Shut down should do it ... Are there by any chance older or duplicate versions of the fonts in another fonts folder, e.g. in your user folder (/Users/username/Library/Fonts)? These should be deleted as well. You could also try to boot in safe mode, keeping the shift key pressed during boot, to clear all font caches.
