### ISSUE TITLE
Partial support under macOS Sierra

### ISSUE THREAD

**Issue by jenskutilek** [jenskutilek/FiraSystemFontReplacement#38]
The existing fonts are only shown in some places in macOS Sierra.

My guess is this is because Apple is now shipping the main system fonts as TTFs with GX variation technology, so the font selection mechanism likely has changed.

The Fira fonts would have to be checked for if the internal names still match with the names of the new system font versions, and then probably the Fira fonts would have to be rebuilt as GX fonts as well.

In addition, Apple is now shipping new families with macOS, for which there is are no corresponding Fira fonts:
- SF Compact Display
- SF Compact Rounded
- SF Compact Text
- SF NS Display Condensed
- SF NS Text Condensed

I’m too busy right now to look into this.

**Comment by benmeroff** [comment]
I have RoboFont on my Mac here but haven't used it in a while, let me know what I could do to help and I'd be glad to assist!  I know for a fact that I can rename and change font family and internal variation names, and I have access to Sierra should I need the new system font.

**Comment by jenskutilek** [comment]
Thanks for your offer! I haven't figured out what needs to be done to get the fonts working yet.

For future reference: The named instances in SFNSText are:
- .SFNSText
- .SFNSText-Medium
- .SFNSText-Semibold
- .SFNSText-Bold
- .SFNSText-Light
- .SFNSText-Heavy

**Comment by jayar42** [comment]
I'm glad you guys are working on this. I haven't a clue.

**Comment by benmeroff** [comment]
It looks like @HiKay has a working method to replace the system font within macOS Sierra, and he's currently looking into a way to support custom fonts:

**https://github.com/HiKay/macOSLucidaGrande**

I unfortunately can't be much help with the coding aspect of this, but if any font work needs to be done with Fira let me know.  Hopefully his work can at least point us in the right direction...

**Comment by CodeBrauer** [comment]
Hope there will be a fix! Would like to see fira sans on macOS again!

**Comment by wan721** [comment]
I miss Fira fonts so much!

**Comment by Fohrbach** [comment]
I agree with wan721. Please update FiraFontSystemReplacement for Sierra! Thanks a lot in advance!

**Comment by Skyyblaze** [comment]
If there's anything I, as mere OSX user, can do to help with Sierra support I would be up for it aswell. My Macbook is currently running on Yosemite and the main reason I'm not updating is the missing custom-font options in Sierra. I wouldn't even mind updating to El Capitan only but apparently I'm "not allowed" anymore according to Apple so I'm stuck on Yosemite for the time being.

**Comment by jenskutilek** [comment]
Finally we have a first version for Sierra! Check out the [Releases](https://github.com/jenskutilek/FiraSystemFontReplacement/releases) section.
