### ISSUE TITLE
macOS Support ?

### ISSUE THREAD

**Issue by danywalls** [jenskutilek/FiraSystemFontReplacement#39]
Should will work on MacOSX Sierra?

**Comment by bowlandspoon** [comment]
Yes, works on OSX El Capitan and others, check main page for details.

**Comment by danywalls** [comment]
@bowlandspoon on MacOSX Sierra dont able to change menu fonts or system preferences, it only able change font for desktop icons.

**Comment by bowlandspoon** [comment]
Sorry I misread your comment. Currently only partial support for Sierra as you have said. Please read the main page.

**Comment by danywalls** [comment]
thanks
