### ISSUE TITLE
A password input field, nothing shows when the password is entering.

### ISSUE THREAD

**Issue by Wielosmakowy** [jenskutilek/FiraSystemFontReplacement#41]
v4.106.2
MacOS 10.12.6

Examples

Safari 11.0 Seed 2:
![zrzut ekranu 2017-07-20 o 05 54 14](https://user-images.githubusercontent.com/9307391/28399890-1ff56b96-6d10-11e7-85a2-5dc3f9404a7c.png)

Dashlane 4.8.3:
![zrzut ekranu 2017-07-20 o 05 54 58](https://user-images.githubusercontent.com/9307391/28399898-2fb4444e-6d10-11e7-986e-4d8a00bd5702.png)

System Preferences (MacOS Sierra 10.12.6)
![zrzut ekranu 2017-07-20 o 05 55 22](https://user-images.githubusercontent.com/9307391/28399900-37b7026c-6d10-11e7-93ba-7687eca5080c.png)

But, some apps show signs normally.

![zrzut ekranu 2017-07-20 o 05 59 38](https://user-images.githubusercontent.com/9307391/28399971-a797dbf6-6d10-11e7-9f4b-3c65138096c3.png)

**Comment by jenskutilek** [comment]
My first guess is that different applications use different placeholder characters in password dialogs, and not all of them are present in Fira Sans. Will check ...

**Comment by dbarros** [comment]
I'm also seeing the same thing. At first I thought my keyboard(s) were broken.

**Comment by jenskutilek** [comment]
Fixed in 4573f4f70ae0d90fe87764073ecc2e3066d75901.
