### ISSUE TITLE
Up and down arrows not correct in SourceTree

### ISSUE THREAD

**Issue by hamishlawson** [jenskutilek/FiraSystemFontReplacement#42]
Up and down arrows are not correctly displayed in the _Interactive Rebase_ dialog box for the SourceTree version control tool:

<img width="545" alt="sourcetree-up-down-arrows" src="https://user-images.githubusercontent.com/13153486/28618719-46f1c4e6-71fd-11e7-8838-25848f3a3fa0.png">

**Comment by jenskutilek** [comment]
This is related to #41, there are some glyphs missing in the current font. Hope to fix soon.

**Comment by jenskutilek** [comment]
Fixed in 4573f4f70ae0d90fe87764073ecc2e3066d75901.
