### ISSUE TITLE
AirDrop - Character missing

### ISSUE THREAD

**Issue by mawmawmawm** [jenskutilek/FiraSystemFontReplacement#43]
I believe this should be a dash.
![d](https://user-images.githubusercontent.com/9080951/28898184-5d5e951e-7799-11e7-830c-f62d06137ff5.png)

**Comment by coopercontent** [comment]
No, it should be a hyphen.

The en dash in the the first instance of "Wi-Fi" above is incorrect.

**Comment by jenskutilek** [comment]
Of course the font contains hyphens and dashes … I wonder what character is used there. Any way to find out? Can the text from a button be copied?

**Comment by jenskutilek** [comment]
OK, I found it. Should be U+2010 (hyphen) or U+2011 (non-breaking hyphen).

**Comment by jenskutilek** [comment]
Fixed in 72a3df2.
