### ISSUE TITLE
Bold characters missing?

### ISSUE THREAD

**Issue by CodeBrauer** [jenskutilek/FiraSystemFontReplacement#46]
![bildschirmfoto 2017-08-16 um 12 08 45](https://user-images.githubusercontent.com/2059754/29358539-b214f188-827b-11e7-9ae1-ac9bb04ed8d2.png)

Sierra 10.12.0, rebooted once (cause the installation forced me to reboot) - after this shut down completely and started again

**Comment by splorp** [comment]
It could have something to do with the old version of Sierra you’re running.

I’m on Sierra 10.12.6 and don’t see this issue at all.


![screenshot 2017-08-16 12 35 31](https://user-images.githubusercontent.com/29835/29379474-d30e3e7c-827f-11e7-8034-556c982ec69d.png)

**Comment by CodeBrauer** [comment]
Will try after updating macOS

**Comment by CodeBrauer** [comment]
Updated macOS to latest version - works fine now, thanks
