### ISSUE TITLE
Xcode scheme platform context menu

### ISSUE THREAD

**Issue by mickeyl** [jenskutilek/FiraSystemFontReplacement#47]
For some reason, this Xcode context menu gets its metrics wrong – which leads to a duplication / overflow of entries while you're trying to select one.

![bildschirmfoto 2017-08-28 um 09 35 15](https://user-images.githubusercontent.com/167469/29763633-3f9c3e1a-8bd4-11e7-80b0-247240ac7834.png)

**Comment by splorp** [comment]
Your screenshot indicates that Fira is not even being used in this menu. Could that be part of the problem?

**Comment by jenskutilek** [comment]
Fira doesn’t replace the ‘SF Display’ styles yet. The display styles are sometimes used in weird places where you wouldn’t expect them (they are meant for large font sizes). Maybe XCode menus are one of these places, so you would see SF there even if Fira is installed.

**Comment by mickeyl** [comment]
I have since reinstalled the latest version and found Xcode showing Fira in this very menu – alas with the same broken vertical metrics:

![bildschirmfoto 2017-08-31 um 15 07 55](https://user-images.githubusercontent.com/167469/29961922-7955c330-8f01-11e7-8eeb-a3d4e665df7d.png)

**Comment by mickeyl** [comment]
Closing this, as I have severe doubts that FiraSans has something to do with it. A fresh upgrade to HighSierra emits the same behavior. Perhaps an incompatibility with my display (37", 3840 x 1600).

**Comment by jenskutilek** [comment]
Sorry I couldn’t be of help ... I just wanted to check again, just to notice that XCode has already been automatically ugraded to version 9 on my machine (I don’t use XCode regularly).  In XCode 9 this menu that you showed isn’t using Fira at all for whatever reason.
