### ISSUE TITLE
Umlaute result in blank Space

### ISSUE THREAD

**Issue by karkraeg** [jenskutilek/FiraSystemFontReplacement#49]
Hi! German Umlaute (ä,ö,ü) result in a blank space after them in file or folder names. 

See this visual example: https://transfer.sh/6tLbA/umlaut.mov

**Comment by jenskutilek** [comment]
Is that by any chance on macOS 10.13 and the new APFS file system?

**Comment by jenskutilek** [comment]
Nevermind, I could replicate it on the current system. The problem appears when an accented character is not entered in its precomposed form (‘Ü’ = U+00DC), but as a sequence of base letter and combining diacritic (‘Ü’ = U+0055 U+0308). I don’t know why though, as the diacritic has a width of 0 in the font.

**Comment by karkraeg** [comment]
So there is no way to change this behavour?

**Comment by jenskutilek** [comment]
I'll have to investigate … if it works in the default font, it should be possible to fix it.

**Comment by splorp** [comment]
Does this have anything to do with the regional language or keyboard settings of the OS? I’m using the 4.106.4 release of the fonts under Sierra (10.12.6) and cannot duplicate this issue using US settings. I am entering Ü (and other umlaut’d characters) using the “option-u -> character” keystrokes.

**Comment by jenskutilek** [comment]
Without having confirmed, I guess option-shift-u results in the precomposed Ü character. I entered the sequence U+0055 U+0308 via the "Show Emoji & Symbols" palette, showing the extra space. In theory, the result of both input methods should be equivalent by Unicode rules.

**Comment by jenskutilek** [comment]
I think I have found it … it seems there is a bug in [glyphsLib](https://github.com/googlei18n/glyphsLib) so the widths for the uppercase variants of the combining diacritics is not set to 0.

**Comment by jenskutilek** [comment]
Should be fixed in the latest release, [v4.106.5](https://github.com/jenskutilek/FiraSystemFontReplacement/releases/tag/v4.106.5).
