### ISSUE TITLE
High Sierra Compatibility

### ISSUE THREAD

**Issue by karkraeg** [jenskutilek/FiraSystemFontReplacement#50]
Hi! Is FiraSystemFontReplacement compatible with macOS 10.13 High Sierra?

**Comment by jenskutilek** [comment]
I checked with the public beta a while ago, and it seemed to work well. Haven’t tried the final release though.

**Comment by karkraeg** [comment]
I just jumped in at the deep end – it’s working fine on 10.13 final. Thanks!
